name = "ARMLive"
uuid = "3cf54da3-541f-4d42-bdd0-41bf6096b485"
version = "0.0.1"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Dates = "1"
DelimitedFiles = "1"
JSON3 = "1.14.3"
Logging = "1"
NCDatasets = "0.14.9"
PrettyTables = "3.1.0"
Printf = "1"
Reexport = "1.2.2"
Statistics = "1"
julia = "^1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
