[deps]
ARMLive = "3cf54da3-541f-4d42-bdd0-41bf6096b485"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"

[compat]
DocumenterVitepress = "0.2"